export const SORTED_BULLETIN_OCG_IDS = [1, 5, 3, 2, 4];

export const OG_ODDS_LIST = {
  [SORTED_BULLETIN_OCG_IDS[0]]: [0, 1, 2],
  [SORTED_BULLETIN_OCG_IDS[1]]: [25, 26],
  [SORTED_BULLETIN_OCG_IDS[2]]: [6, 7, 8, 9, 10],
  [SORTED_BULLETIN_OCG_IDS[3]]: [3, 4, 5],
  [SORTED_BULLETIN_OCG_IDS[4]]: [11, 12],
};
